# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chattingName', models.CharField(max_length=50)),
                ('historyMessage', models.CharField(max_length=32000))
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
            ],
        )
    ]

