# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]

